name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_date: ["1203", "1205", "1207", "1208", "1209", "1210", "1212", "1213", "1214", "1215"]
      fail-fast: false
    
    env:
      RANDOM_SEED: 0

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run experiment for specific date
      run: |
        cd src
        echo "Running for file_date=${{ matrix.file_date }} with RANDOM_SEED=$RANDOM_SEED"
        python main.py --file_date "${{ matrix.file_date }}" --test
        echo "Experiment completed for file_date=${{ matrix.file_date }} with RANDOM_SEED=$RANDOM_SEED"