name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "data/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "data/**"
      - ".github/workflows/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          # Find all directories in data/ (consist only of numbers)
          DATES=$(ls -d data/*/ | xargs -n 1 basename | grep -E '^[0-9]{8}$' | sort -n | jq -R -s -c 'split("\n")[:-1]')
          echo "Found dates: $DATES"
          echo "matrix=$DATES" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_date: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false
    
    env:
      RANDOM_SEED: 0
      OSRM_HOST: "http://localhost:5000"
      DC_LONGITUDE: "121.40712"
      DC_LATITUDE: "25.083282"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run experiment for specific date
      run: |
        cd src
        echo "Running for file_date=${{ matrix.file_date }} with RANDOM_SEED=$RANDOM_SEED"
        python main.py --file_date "${{ matrix.file_date }}" --test
        echo "Experiment completed for file_date=${{ matrix.file_date }} with RANDOM_SEED=$RANDOM_SEED"